name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.repository == '497363983/useBitable'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm install --frozen-lockfile
      - name: Build Test
        run: npm run build
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
      fail-fast: false
    if: github.repository == '497363983/useBitable'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install
        run: npm install --frozen-lockfile
      - name: Build Test
        run: npm run build
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm run test